version: 2

updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # We don't want automatic language updates for minor and major versions
      # (see ADR 17).
      - dependency-name: "library/python"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "library/golang"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
