language: go

go:
  - 1.x
env:
  - GO111MODULE=on

script:
  - make all
  - docker-compose -f test/docker-compose.yml up -d
  - go test ./pubsub

notifications:
  email:
    on_success: never
    on_failure: never
