name: Bookkeeping
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  pr2project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign author
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            const { repo, payload: { pull_request: { number, user } } } = context;
            if (user.type === "User") {
              await github.rest.issues.addAssignees({
                ...repo,
                issue_number: number,
                assignees: [user.login],
              })
            }
      - name: Add to project board
        if: ${{ github.event.pull_request.user.type == 'User' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
          PR_ID: ${{ github.event.pull_request.node_id }}
          PROJECT_ID: PVT_kwDOAKWJJc0NFw
          STATUS_FIELD_ID: PVTSSF_lADOAKWJJc0NF81r2g
          IN_REVIEW_OPTION_ID: 16912349
        run: |
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $pr:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $pr}) {
                item { id }
              }
            }' -f project=$PROJECT_ID -f pr=$PR_ID --jq '.data.addProjectV2ItemById.item.id')"
          gh api graphql -f query='
            mutation (
              $project: ID!
              $item: ID!
              $status_field: ID!
              $status_value: String!
            ) {
              set_status: updateProjectV2ItemFieldValue(input: {
                projectId: $project
                itemId: $item
                fieldId: $status_field
                value: { singleSelectOptionId: $status_value }
              }) {
                projectV2Item { id }
              }
            }' -f project=$PROJECT_ID -f item=$item_id -f status_field=$STATUS_FIELD_ID -f status_value=$IN_REVIEW_OPTION_ID
