name: Bookkeeping
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  pr2project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign author
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            const { repo, payload: { pull_request: { number, user } } } = context;
            if (user.type === "User") {
              await github.rest.issues.addAssignees({
                ...repo,
                issue_number: number,
                assignees: [user.login],
              })
            }
