name: Container

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
          ignore: DL3008
          # We do not currently pin versions of apt packages.

  docker:
    name: "Build'n'push"
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Highest priority tag determines the image version
          tags: |
            type=raw,value={{date 'YY.MM.DD'}}-{{branch}}-{{sha}},priority=1000
            type=ref,event=branch,priority=900

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            branch=${{ github.ref_name }}
            version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            revision=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
