name: Yamllint
on:
  push:
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Install yamllint'
        run: pip install yamllint
      - run: yamllint .
